{% set component_name = "msgs" %}
{% set repo_name = "gz-" + component_name %}
{% set version = "10.3.0" %}
{% set major_version = version.split('.')[0] %}
{% set name = repo_name + major_version %}
{% set component_version = component_name + major_version %}
{% set cxx_name = "lib" + name %}
{% set python_name = name + "-python" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/gazebosim/{{ repo_name }}/archive/{{ repo_name }}{{ major_version }}_{{ version }}.tar.gz
    sha256: a93a59379b1179b22a2995a3888daf18486f945565170fd97446d6a58b543b25
    patches:
      - win_enable_py_tests.patch

build:
  number: 0

outputs:
  - name: {{ cxx_name }}
    script: build_cxx.sh  # [unix]
    script: bld_cxx.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage(cxx_name, max_pin='x') }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
        - ninja
        - cmake
        - pkg-config
        - python
        # We need all host deps also in build for cross-compiling
        - libgz-math7  # [build_platform != target_platform]
        - libgz-tools2  # [build_platform != target_platform]
        - tinyxml2  # [build_platform != target_platform]
        - libabseil  # [build_platform != target_platform]
        - libprotobuf  # [build_platform != target_platform]
      host:
        - libgz-math7
        - libgz-tools2
        - tinyxml2
        - libabseil
        - libprotobuf
        - dlfcn-win32  # [win]
      run:
        - python
    test:
      commands:
        - test -f ${PREFIX}/include/gz/{{ component_version }}/gz/{{ component_name }}.hh  # [not win]
        - test -f ${PREFIX}/lib/lib{{ name }}.so  # [linux]
        - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
        - test -f ${PREFIX}/lib/cmake/{{ name }}/{{ name }}-config.cmake  # [not win]
        - if not exist %PREFIX%\\Library\\include\\gz\\{{ component_version }}\\gz\\{{ component_name }}.hh exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\{{ name }}.lib exit 1  # [win]
        - if not exist %PREFIX%\\Library\\bin\\{{ name }}.dll exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\cmake\\{{ name }}\\{{ name }}-config.cmake exit 1  # [win]

  - name: {{ python_name }}
    build:
      noarch: python
    script: build_py.sh  # [unix]
    script: bld_py.bat  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - ninja
        - cmake
        - pkg-config
        - python
        # We need all host deps also in build for cross-compiling
        - libgz-math7  # [build_platform != target_platform]
        - libgz-tools2  # [build_platform != target_platform]
        - tinyxml2  # [build_platform != target_platform]
        - libabseil  # [build_platform != target_platform]
        - libprotobuf  # [build_platform != target_platform]
      host:
        - libgz-math7
        - libgz-tools2
        - tinyxml2
        - libabseil
        - libprotobuf
        - python
        - protobuf
        - pytest
        - dlfcn-win32  # [win]
      run:
        - python  >=3.8
        - protobuf
    test:
      commands:
        - pip check
      requires:
        - pip
      imports:
        - gz.msgs10

  - name: {{ name }}
    build:
      run_exports:
        - {{ pin_subpackage(cxx_name, max_pin='x') }}
    requirements:
      run:
        - {{ pin_subpackage(cxx_name, exact=True) }}
        - {{ pin_subpackage(python_name, max_pin='x.x.x') }}
    test:
      commands:
        - test -f ${PREFIX}/include/gz/{{ component_version }}/gz/{{ component_name }}.hh  # [not win]
        - test -f ${PREFIX}/lib/lib{{ name }}.so  # [linux]
        - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
        - test -f ${PREFIX}/lib/cmake/{{ name }}/{{ name }}-config.cmake  # [not win]
        - if not exist %PREFIX%\\Library\\include\\gz\\{{ component_version }}\\gz\\{{ component_name }}.hh exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\{{ name }}.lib exit 1  # [win]
        - if not exist %PREFIX%\\Library\\bin\\{{ name }}.dll exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\cmake\\{{ name }}\\{{ name }}-config.cmake exit 1  # [win]
      requires:
        - pip
      imports:
        - gz.msgs10

about:
  home: https://github.com/gazebosim/{{ repo_name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: Messages for Gazebo robot simulation.

extra:
  feedstock-name: {{ repo_name }}
  recipe-maintainers:
    - wolfv
    - traversaro
    - j-rivero
    - Tobias-Fischer
